// server.js
import express from 'express';
import bodyParser from 'body-parser';
import cors from 'cors';
import fetch from 'node-fetch'; // Om du använder Node < 18, annars är fetch inbyggt

const app = express();
const PORT = 3000;

// Middleware
app.use(cors());
app.use(bodyParser.json());
app.use(express.static('public')); // Serverar frontend-filer

// Konfiguration
const OLLAMA_URL = 'http://localhost:11434/api/generate';
const MODEL_NAME = 'llama3'; // Ändra till 'mistral' om du föredrar den

app.post('/analyze', async (req, res) => {
    const { text } = req.body;

    if (!text) return res.status(400).json({ error: 'Ingen text angiven.' });

    // "THE SCORECARD PROMPT" - Tvingar AI:n att betygsätta texten matematiskt
    // server.js (ersätt den gamla prompt-delen med detta)

// En neutral prompt som analyserar mönster istället för att jaga fel
const systemPrompt = `You are an objective linguistic analyst. Your task is to analyze the provided text and determine if it was likely written by a human or generated by an Artificial Intelligence (LLM).

You must remain neutral and evaluate the text based on these linguistic principles:

1. **Burstiness (Variance):** - Humans tend to have high "burstiness" – a mix of very short, simple sentences and long, complex ones. 
   - AI models often produce text with a very uniform, consistent rhythm and sentence length.

2. **Perplexity (Predictability):**
   - AI text is statistically probable. It chooses the most likely next word, resulting in "smooth" but often generic text.
   - Human text often contains surprising word choices, slang, typos, emotional nuance, or specific vivid details that an AI wouldn't hallucinate (low probability words).

3. **Patterns vs. Personality:**
   - Look for specific AI "tells" (overuse of transition words like "Furthermore", "In conclusion", or words like "delve", "tapestry") BUT weigh them against human traits (personal anecdotes, strong opinions, stylistic quirks).

INSTRUCTIONS:
- First, perform a balanced analysis of the text structure and vocabulary.
- Compare the evidence for "Human" vs "AI".
- Do not default to "AI" just because the grammar is good.
- Do not default to "Human" just because the text is polite.

You must output your analysis FIRST. 
At the very END of your response, you must write exactly one of these two decisions:
FINAL_DECISION: [Human-written] or [FINAL_DECISION: [LLM-generated]`;

// OBS: Se till att resten av koden (fullPrompt, fetch etc.) är kvar som innan.

    const fullPrompt = `${systemPrompt}\n\nTEXT TO ANALYZE:\n"${text}"`;

    try {
        const response = await fetch(OLLAMA_URL, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                model: MODEL_NAME, // Använd 'mistral' eller 'mistral-nemo'
                prompt: fullPrompt,
                stream: false,
                // I options-objektet i server.js
                    options: {
                        temperature: 0.0,  // Behåll 0.0 för konsekventa svar (viktigt för en detektor)
                        seed: 42,          // Bra, behåll detta
                        top_k: 20,         // Ändra från 1 till ca 40. Detta låter modellen överväga fler koncept innan den väljer ord.
                        top_p: 0.5         // Standardvärde som ger bra balans.
}
            }),
        });

        const data = await response.json();
        res.json({ result: data.response });

    } catch (error) {
        console.error('Fel:', error);
        res.status(500).json({ error: 'Något gick fel.' });
    }
});

app.listen(PORT, () => {
    console.log(`Servern körs på http://localhost:${PORT}`);
});